services:
  - type: web
    name: studentdeals-api
    env: node
    plan: free
    buildCommand: npm install -g pnpm && NODE_ENV=development pnpm install --frozen-lockfile && pnpm --filter api build
    startCommand: pnpm --filter api start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
